// ★ Tool Registry — 제품 본체 (design §0, §8).
// Every feature registers here as { name, description, input_schema, handler }.
// MCP / CLI / HTTP adapters are all generated by walking this registry —
// no hand-written routing, no UI-only logic.

import { validate } from "../lib/validate.js";
import { getDb } from "../db/index.js";
import { bus } from "../lib/bus.js";
import { seedBuiltins } from "../templates/builtins.js";

const tools = new Map();

// def: { name, description, input_schema, handler, read?:boolean }
// handler signature: (args, ctx) => result   where ctx = { db, bus }
export function register(def) {
  if (!def?.name || typeof def.handler !== "function") {
    throw new Error("register: name and handler are required");
  }
  if (tools.has(def.name)) throw new Error(`duplicate tool: ${def.name}`);
  tools.set(def.name, {
    read: false,
    input_schema: { type: "object", properties: {} },
    ...def,
  });
}

export function list() {
  return [...tools.values()];
}

export function get(name) {
  return tools.get(name);
}

// Adapter-facing: just the public surface (name/description/schema/read).
export function schemas() {
  return list().map(({ name, description, input_schema, read }) => ({
    name, description, input_schema, read,
  }));
}

function defaultCtx() {
  return { db: getDb(), bus };
}

// Validate input against the tool's schema (filling defaults), then run.
export async function execute(name, args = {}, ctx = defaultCtx()) {
  const tool = tools.get(name);
  if (!tool) throw new Error(`unknown tool: ${name}`);
  const { valid, errors, value } = validate(tool.input_schema, args ?? {});
  if (!valid) {
    const err = new Error(`invalid input for ${name}: ${errors.join("; ")}`);
    err.code = "INVALID_INPUT";
    err.errors = errors;
    throw err;
  }
  return tool.handler(value, ctx);
}

// Modules call registerAll() at import time; we also expose a loader so
// adapters can ensure every tool module is imported before walking the registry.
let _loaded = false;
export async function loadTools() {
  if (_loaded) return;
  _loaded = true;
  await Promise.all([
    import("./service.tools.js"),
    import("./slide.tools.js"),
    import("./content.tools.js"),
    import("./search.tools.js"),
    import("./present.tools.js"),
    import("./media.tools.js"),
    import("./template.tools.js"),
  ]);
  // built-in slide kinds are templates too — seed them now that content tools
  // (whose schemas define generator params) are registered.
  seedBuiltins(getDb(), get);
}
